### ISSUE TITLE
wrong duplicates/overlaps in many spaces

### ISSUE THREAD

**Issue by UserAbility** [UserAbility/metroid#11] opened 2017-03-13 05:39 UTC
<img width="874" alt="screen shot 2017-03-12 at 10 33 33 pm" src="https://cloud.githubusercontent.com/assets/3986650/23842871/a455c6c6-0774-11e7-9aa9-6f7249a5c593.png">

**Comment by theefxman** [comment] 2017-03-13 06:55
This is caused by over-accurate original game rendering. In the original game some of the structures would bleed off the bottom of the screen. I guess it didn't matter in the original because the visible space they occupied was not rendered. I have developed logic that auto trims the bottom of our rooms. :)

**Comment by theefxman** [comment] 2017-03-13 16:15
![issues_fixed](https://cloud.githubusercontent.com/assets/4247833/23863699/62ba639c-07de-11e7-8df8-811c519fd30f.png)
 I believe this issue is fixed in the next code release

**Closed as completed** 2017-03-15 00:29 UTC
